.pipeline: &pipeline
  runner:
    cpus: 2
  docker:
    image: node:20.11.1
  stages:
    - name: 启用pnpm
      script: corepack enable pnpm
    - name: 安装依赖
      script: pnpm install
    - name: test
      script: pnpm run test
    - name: build
      script: pnpm run build

release:
  push:
    - <<: *pipeline